### ISSUE TITLE
Make things more functional

### ISSUE THREAD

**Issue by jenius** [carrot/roots-mini#19]
So I've been reading some functional programming propaganda and I must admit they have a few convincing arguments. Mainly that lot of nasty bugs result from shared state, which from past experience I can say is without a doubt true. So since we are still nice and simple at the beginning stages, I'm curious how things would look if we made them a little more functional, and reduced some of the shared state in the architecture. At the start perhaps a branch to see what the difference in the API and structure would be, then we can evaluate it from there.

**Comment by hhsnopek** [comment]
Got any articles to list here? :smile:

**Comment by jenius** [comment]
https://drboolean.gitbooks.io/mostly-adequate-guide/

**Comment by jenius** [comment]
Closing this out for now, things are looking pretty good
