### ISSUE TITLE
Including jade partials fails compilation silently

### ISSUE THREAD

**Issue by elvingm** [carrot/roots-mini#48]
In my `index.jade` when I attempt to include other files using any of the following:

`include ./_includes/head.jade`
`include _includes/head.jade`
`include _includes/head`

Fails without errors or just doesn't compile during either `watch` or `compile`.
Using parentheses around the file name after the `include` keyword, however, throws an error saying file or directory not found even if file/directory does exist.

**Comment by kylemac** [comment]
the reason this errors silently is we aren't handling an error in the jade plugin, here: https://github.com/carrot/roots-mini/blob/develop/lib/plugins/jade_plugin.js#L21-L22

**Comment by kylemac** [comment]
closed via https://github.com/carrot/roots-mini/commit/e3d8dd132c991e2b4d9ee574bc2271c1ea430f53 wherein we use our own fork of `jade-loader` that doesn't do a `jade.compileClient` that needs to be eval'd, but rather a `jade.compile` that we marshall along as JSON
