### ISSUE TITLE
Updates to partials doesn't trigger compilation during watch

### ISSUE THREAD

**Issue by elvingm** [carrot/roots-mini#49]
In `index.css`, I import various partials prefixed with `_`.
Unless I remove the `**/_*` matcher in the `ignores` option, it does not recompile if partials prefixed with a `_` are updated. If that ignore string is removed, however, CSS files for each partial are then generated in the `public` folder.

**Comment by kylemac** [comment]
@elvingm if you remove the `**/_*` matcher (and they are dropped in public) does it trigger a recompile when they are edited?

**Comment by elvingm** [comment]
@kylemac yes. It recompiles after then if the partials are updated. If that matcher isn't removed it'll only recompile if the main `index.css` is saved.

**Comment by elvingm** [comment]
@kylemac Update on this one to provide a little more detail I'm facing.
Removing the matcher triggers a recompile if a change is made to a partial, but files that include that partial do not get rebuilt.

e.g. A change to `_navbar.css` rebuilds `_navbar.css` in the public folder, but `index.css` which includes `_navbar.css` does not get rebuilt to reflect those changes.

**Comment by kylemac** [comment]
helpful. keep working pushing through this - and we'll get to a fix soon.

**Comment by jenius** [comment]
The fix to this is being more careful with compiler and watcher ignores. Will have to dig in to the browser sync plugin.

**Comment by kylemac** [comment]
@elvingm to give you a starting point: 

we pass in `opts.server` (from the cmd line, or from a project's `app.js`) into the [browsersync-webpack-plugin](https://github.com/Va1/browser-sync-webpack-plugin) here: https://github.com/carrot/roots-mini/blob/develop/lib/config.js#L158

...you can review browsersync's options on [their docs](https://browsersync.io/docs/options/).

**Comment by kylemac** [comment]
@elvingm verify that #53 does the trick and close this sucker, if so :raised_hands:

**Comment by elvingm** [comment]
@kylemac :+1: looks good!
