### ISSUE TITLE
CI for Windows Support

### ISSUE THREAD

**Issue by declandewet** [carrot/roots-mini#8]
Roots, in its early days, didn't play very nicely with Windows. Perhaps we should add some CI for Windows?

[AppVeyor](http://www.appveyor.com/) is CI for Windows and free for open source

**Comment by jenius** [comment]
Absolutely. I would love to have this set up from the start

**Comment by declandewet** [comment]
It seems its setup:

![](https://infinit.io/_/WRv9YKJ.png)

**Comment by kylemac** [comment]
I had given this a shot the other day to see how involved it was -- forgot to delete it. should be gone now

**Comment by declandewet** [comment]
what was the verdict @kylemac ?

**Comment by kylemac** [comment]
verdict: it was more complicated than I cared to deal with at the time.

**Comment by jenius** [comment]
Closing because ☝️ . Can re-open later if this becomes a priority, but right now priorities are adding features we need and shipping quick.
