### ISSUE TITLE
Separate production config

### ISSUE THREAD

**Issue by jenius** [carrot/roots-mini#92]
So this was something we used with frequency in roots. It's possible now using environment variables and if statements, but ideally we'd have a smoother way to do it. It seems like in roots, the most normal use case was loading the dev config but allowing the user to override what they want from this in a separate file, so I feel like perhaps that would be the best route for us here.

- `app.js` exports whatever
- `app.environment.js` exports a merged with `app.js`, with priority given to the environment file

Thoughts?

**Comment by kylemac** [comment]
I am mega in favor of this. I've always felt that the repetition we had in the old `app.production.coffee`s was unfortunate

**Comment by kylemac** [comment]
closed via https://github.com/carrot/roots-mini/pull/93
