### ISSUE TITLE
Validate webpack config

### ISSUE THREAD

**Issue by declandewet** [carrot/roots-mini#97]
found this gem earlier this morning: https://github.com/js-dxtools/webpack-validator

**Comment by kylemac** [comment]
this may not work for us because we don't directly take all webpack configs - we sprinkle it in with our own configs and browsersyncs and such. also, we're doing pretty solid Joi validation on our own already

**Comment by jenius** [comment]
We could run it on the result from our function that converts our config to webpack config though

**Comment by jenius** [comment]
However it looks like [they don't have the `allowUnknown` option on](https://github.com/js-dxtools/webpack-validator/blob/master/src/index.js#L59), which means any plugin that sets options directly on webpack will cause an error. This could probably be fixed with a pull request though 😁

**Comment by jenius** [comment]
I'm going to close this out because I don't think it brings a huge value to the project, we already validate our own options, and we'd have to fork it in order to get it working anyway.
